spring:
  application:
    name: estore-ws
  info:
    git:
      location: classpath:META-INF/git.properties
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    driver-class-name: org.postgresql.Driver
    #username:
    #password:

logging:
  config: /opt/app/java/config/logback.xml

server:
  port: 8020
  servlet:
    context-path: /app
    session:
      cookie:
        http-only: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

management:
  info:
    git:
      mode: simple
  endpoint:
    health:
      show-details: always
  server:
    port: 8181
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,health,prometheus"

