---
# Source: estore/charts/spring-boot-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-app
  labels:
    app.kubernetes.io/name: spring-boot-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/component: estore
    app.kubernetes.io/part-of: payments-product
    helm.sh/chart: spring-boot-app-0.1.0
data:
  application.yml: |
    