---
# Source: estore/charts/spring-boot-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  labels:
    app.kubernetes.io/name: spring-boot-app
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/component: estore
    app.kubernetes.io/part-of: payments-product
    helm.sh/chart: spring-boot-app-0.1.0
    metrics/spring-boot: 'true'
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: app
      protocol: TCP
      name: app
    - port: 8181
      targetPort: mgmt
      protocol: TCP
      name: mgmt
  selector:
    app.kubernetes.io/name: spring-boot-app
    app.kubernetes.io/instance: release-name
