---
# Source: estore/charts/persistence/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence
  labels:
    app.kubernetes.io/name: persistence
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/component: estore
    app.kubernetes.io/part-of: estore-product
    helm.sh/chart: persistence-0.1.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: persistence
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: persistence
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/component: estore
        app.kubernetes.io/part-of: estore-product
    spec:
      containers:
        - name: persistence
          #image: 'localhost/estore/:'
          image: ':'
          imagePullPolicy: Always
          ports:
            - name: persistence
              containerPort: 1234
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - docker-healthcheck.sh
            
          volumeMounts:
            - name: persistencevolume
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
            
      volumes:
        - name: persistencevolume
          hostPath:
            path: db-estore
            type: DirectoryOrCreate

      imagePullSecrets:
        - name: dtrcred
