apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/component: {{ .Values.image.organization }}
    app.kubernetes.io/part-of: {{ .Values.global.partOf }}
    helm.sh/chart: {{ include "service.chart" . }}
data:
  application.yml: |
{{ .Values.application.config | indent 4}}