{{- if or (.Values.global.ingress.enabled) (.Values.ingress.enabled) -}}
{{- $name := include "service.name" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/component: {{ .Values.image.organization }}
    app.kubernetes.io/part-of: {{ .Values.global.partOf }}
    helm.sh/chart: {{ include "service.chart" . }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $name }}
              servicePort: app
{{- if .Values.ingress.host }}
      host: {{ .Values.ingress.host | quote }}
{{- end }}
{{- end }}
