#Overide global value of the spring boot application chart value
global:


conditions:
  estore-auth: true
  estote-ws: false
  estote-web: false
  db-estore: true
  db-migration-estore: false

db-estore:
  nameOverride: db-estore
  image:
    repository: postgres
    tag: 10.4
  persistenceVolume:
    mount: false
    mountPath: /var/lib/postgresql/data
    hostPath:
      path: /db-estore
    service:
      type: NodePort
      port:
        app: 8080
        mgmt: 9080
      nodePort: 32080
estore-web:
  nameOverride: estore-web
  image:
    repository: estore-web
    tag: 0.0.1-SNAPSHOT
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port:
      app: 8081
      mgmt: 9081
    nodePort: 32081
estore-ws:
  nameOverride: estore-ws
  image:
    repository: estore-rest
    tag: 0.0.1-SNAPSHOT
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port:
      app: 8082
      mgmt: 9082
    nodePort: 32082
estore-auth:
  nameOverride: estore-auth
  image:
    repository: estore-auth-rest
    tag: 0.0.1-SNAPSHOT
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port:
      app: 8083
      mgmt: 9083
    nodePort: 32083


