spring:
      application:
        name: estore-ws
      config:
          name: estore-config
      info:
        git:
          location: classpath:META-INF/git.properties
      url: {{ .Values.asptsm.datasource.url }}
         hikari:
           jdbc-url: {{ .Values.asptsm.datasource.url }}
           driver-class-name: {{ .Values.asptsm.datasource.driver }}
           username: {{ .Values.asptsm.datasource.username }}
           password: {{ .Values.asptsm.datasource.password }}
           schema: {{ .Values.asptsm.datasource.schema }}
           maximum-pool-size: {{ .Values.asptsm.datasource.maximumPoolSize }}
           minimum-idle: {{ .Values.asptsm.datasource.minimumIdle }}
      jpa:
        properties:
          hibernate:
             dialect: org.hibernate.dialect.PostgreSQLDialect
             jdbc.lob.non_contextual_creation: true

    logging:
      config: /opt/app/java/config/logback.xml

    server:
      port: 8020
        session:
          cookie:
            http-only: true
      tomcat:
        remote-ip-header: x-forwarded-for
        protocol-header: x-forwarded-proto

    management:
      info:
        git:
          mode: full
      endpoint:
        health:
          show-details: always
      server:
        port: 8181
      endpoints:
        web:
          base-path: /
          exposure:
            include: "*"