appVersion: 1.0.0-SNAPSHOT

image:
  organization: estore

container:
  port: 1234

service:
  type: NodePort
  port: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: "2"

env: []

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
    exec:
      command:
         - /bin/sh
         - -c
         - docker-healthcheck.sh

nameOverride: ""

persistenceVolume:
  mount: true
  mountPath: /var/lib/postgresql/data
  hostPath: db-estore

global:
  partOf: estore-product
  imageRegistrySecret: dtrcred
  image:
    repositoryServer: localhost
    pullPolicy: Always
    referenceImageDigest: true