global:
  partOf: project-demo
#  imageRegistrySecret: dtrcred
  image:
    repositoryServer: harihar2u/project-demo
    pullPolicy: Always
    referenceImageDigest: true
  nodeSelector:
    enabled: true


nameOverride: ""
appVersion: 1.0.0-SNAPSHOT
image:
  organization: estore
  repository: postgres
  tag: 1.0.0-SNAPSHOT
  tagStr: 1.0.0-SNAPSHOT
container:
  port: 1234
service:
  type: NodePort
  port: 8080
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: "2"
persistenceVolume:
  mount: true
  mountPath:
  hostPath:

env: []
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe: {}




