apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "persistence.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "persistence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/component: {{ .Values.image.organization }}
    app.kubernetes.io/part-of: {{ .Values.global.partOf }}
    helm.sh/chart: {{ include "persistence.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "persistence.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "persistence.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Values.appVersion }}
        app.kubernetes.io/component: {{ .Values.image.organization }}
        app.kubernetes.io/part-of: {{ .Values.global.partOf }}
{{- if .Values.global.image.referenceImageDigest }}
        app.kubernetes.io/image-tag: {{ .Values.image.tagStr }}
{{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          #image: '{{ .Values.global.image.repositoryServer }}/{{ .Values.image.organization }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: persistence
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
{{- if .Values.persistenceVolume.mount }}
          volumeMounts:
            - name: persistencevolume
              mountPath: {{ .Values.persistenceVolume.mountPath }}
{{- end }}
{{- with .Values.env }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.persistenceVolume.mount }}
      volumes:
        - name: persistencevolume
          hostPath:
            path: {{ .Values.persistenceVolume.hostPath }}
            type: DirectoryOrCreate
{{- end }}
{{if .Values.global.imageRegistrySecret}}
      imagePullSecrets:
        - name: {{ .Values.global.imageRegistrySecret }}
{{- end }}
{{- if .Values.global.nodeSelector.enabled }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
