apiVersion: v1
kind: Service
metadata:
  name: {{ include "persistence.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "persistence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/component: {{ .Values.image.organization }}
    app.kubernetes.io/part-of: {{ .Values.global.partOf }}
    helm.sh/chart: {{ include "persistence.chart" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: persistence
      protocol: TCP
      name: persistence
      nodePort: 32080
  selector:
    app.kubernetes.io/name: {{ include "persistence.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
